function filter(){
		 var search
		 value = document.getElementById("search").value.toUpperCase();
		 document.location="search2.jsp?key="+value
	}
	
	
var availableTags = [
	  '#안녕',
      '(여자)아이들',
      '10CM',
      '15& (박지민, 백예린)',
      '2AM',
      '2NE1',
      '2PM',
      '4minute',
      'aespa',
      'AKMU (악뮤)',
      'Anne-Marie',
      'AOA',
      'Apink (에이핑크)',
      'Ariana Grande',
      'ASH ISLAND',
      'B1A4',
      'BewhY (비와이)',
      'BIGBANG',
      'BLACKPINK',
      'BOBBY',
      'Bro',
      'C JAMM',
      'CHEEZE (치즈)',
      'CL',
      'CNBLUE (씨엔블루)',
      'Conan Gray',
      'Crush',
      'DEAN',
      'DJ DOC',
      'Dua Lipa',
      'Ed Sheeran',
      'EXID',
      'EXO',
      'EXO-CBX (첸백시)',
      'EXO-K',
      'f(x)',
      'FTISLAND (FT아일랜드)',
      'F-ve Dolls',
      'GD X TAEYANG',
      'GD&TOP',
      'G-DRAGON',
      'GG (박명수 & G-Dragon)',
      'god',
      'HI SUHYUN',
      'HIGH4 (하이포)',
      'HYNN (박혜원)',
      'iKON',
      'ITZY (있지)',
      'Ja Mezz',
      'Jawsh 685',
      'JUNIEL(서아)',
      'Justin Bieber',
      'Jvcki Wai',
      'Khundi Panda',
      'Lauv',
      'Mariah Carey',
      'Maroon 5',
      'MC몽',
      'MINO (송민호)',
      'MSG워너비',
      'MSG워너비 TOP 8 (별루지, 김정수, 강창모, 정기석, 이동휘, 이상이, 박재정, 원슈타인)',
      'MSG워너비(M.O.M)',
      'MSG워너비(정상동기)',
      'NCT DREAM',
      'NS 윤지',
      'pH-1',
      'PRODUCE 101',
      'Red Velvet (레드벨벳)',
      'Rohann (이로한)',
      'S.M. THE BALLAD',
      'San E',
      'SE7EN',
      'SG 워너비',
      'SHINee (샤이니)',
      'Sia',
      'STAYC(스테이씨)',
      'SUPER JUNIOR (슈퍼주니어)',
      'Supreme Team',
      'SURAN (수란)',
      'Tablo',
      'The Kid LAROI',
      'Tones And I',
      'TWICE (트와이스)',
      'V.O.S',
      'Wanna One (워너원)',
      'WINNER',
      'XIA (준수)',
      'Zion.T',
      '가비엔제이',
      '가인',
      '가호 (Gaho)',
      '강승윤',
      '개리',
      '거미',
      '걸스데이',
      '경서',
      '경서예지',
      '국민의 아들',
      '규현 (KYUHYUN)',
      '긱스 (Geeks)',
      '길구봉구',
      '김나영',
      '김대명',
      '김동률',
      '김범수',
      '김보경 (NEON)',
      '김연우',
      '김예림 (Lim Kim)',
      '김필',
      '김하온 (HAON)',
      '나르샤 (Brown Eyed Girls)',
      '나비',
      '나얼',
      '넉살',
      '노을',
      '닐로(Nilo)',
      '다비치',
      '다이나믹 듀오',
      '달샤벳',
      '댄싱게놈 (유재석, JYP)',
      '동방신기 (TVXQ!)',
      '디셈버',
      '디핵 (D-Hack)',
      '뜨거운 감자',
      '라붐 (LABOUM)',
      '러블리즈',
      '레이디스 코드',
      '레인보우',
      '로꼬',
      '로이킴',
      '로제 (ROSE)',
      '리쌍',
      '린',
      '릴보이 (lIlBOI)',
      '마마무 (Mamamoo)',
      '마이티 마우스',
      '마크툽 (MAKTUB)',
      '매드클라운',
      '머쉬베놈 (MUSHVENOM)',
      '먼데이 키즈 (Monday Kiz)',
      '멜로망스',
      '모모랜드 (MOMOLAND)',
      '문문 (MoonMoon)',
      '미도와 파라솔',
      '미란이 (Mirani)',
      '미쓰에이',
      '민경훈',
      '민서',
      '바닷길 (길 & 바다)',
      '바이브',
      '박경',
      '박명수',
      '박보람',
      '박봄 (Park Bom)',
      '박원',
      '박재범',
      '박지윤',
      '박진영',
      '박효신',
      '반하나',
      '방탄소년단',
      '배치기',
      '백아연',
      '백예린 (Yerin Baek)',
      '백지영',
      '버벌진트',
      '버스커 버스커',
      '버즈',
      '범키',
      '벤',
      '별',
      '보아 (BoA)',
      '보이비',
      '볼빨간사춘기',
      '브라운 아이드 소울',
      '브라운아이드걸스',
      '브레이브걸스',
      '블락비 (Block B)',
      '블락비 바스타즈',
      '블루 (BLOO)',
      '비',
      '비스트',
      '비투비',
      '빅마마',
      '빈지노 (Beenzino)',
      '사이먼 도미닉',
      '산들',
      '샘김 (Sam Kim)',
      '서영은',
      '서인국',
      '서인영',
      '선미',
      '성시경',
      "소녀시대 (GIRLS' GENERATION)",
      "소녀시대-태티서 (Girls' Generation-TTS)",
      '소녀온탑',
      '소유 (SOYOU)',
      '소정 (레이디스 코드)',
      '손담비',
      '송이한',
      '송지은',
      '송하예',
      '숀 (SHAUN)',
      '수지 (SUZY)',
      '수퍼비',
      '순순희',
      '스윙스',
      '스탠딩 에그',
      '승리',
      '시크릿',
      '신예영',
      '신용재 (2F)',
      '신현희와김루트',
      '신화',
      '싸이 (PSY)',
      '싹쓰리 (유두래곤, 린다G, 비룡)',
      '써니힐',
      '씨스타',
      '씨스타19',
      '씨야',
      '아롬',
      '아웃사이더',
      '아이오아이 (I.O.I)',
      '아이유',
      '알리 (ALi)',
      '애프터스쿨',
      '양다일',
      '양요섭',
      '양파',
      '어반자카파',
      '어쿠스틱 콜라보',
      '언니쓰',
      '언터쳐블',
      '에디킴',
      '에릭남 (Eric Nam)',
      '에이트',
      '에일리(AILEE)',
      '에픽하이 (EPIK HIGH)',
      '엔플라잉 (N.Flying)',
      '엠블랙',
      '엠씨더맥스 (M.C the MAX)',
      '여자친구 (GFRIEND)',
      '예성 (YESUNG)',
      '오렌지 캬라멜',
      '오마이걸 (OH MY GIRL)',
      '오반 (OVAN)',
      '오혁',
      '용감한 녀석들',
      '용준형',
      '우디 (Woody)',
      '우원재',
      '울랄라세션',
      '원더걸스',
      '원슈타인',
      '유성은',
      '유승우',
      '유재석',
      '유재환',
      '윤도 (YoonDo)',
      '윤미래',
      '윤민수(바이브)',
      '윤종신',
      '윤하 (YOUNHA)',
      '이무진',
      '이선희',
      '이수 (엠씨더맥스)',
      '이승기',
      '이승철',
      '이예준',
      '이적',
      '이정',
      '이하이',
      '이현',
      '이효리',
      '인크레더블',
      '인피니트',
      '임재현',
      '임정희',
      '임창정',
      '임한별',
      '잔나비',
      '장덕철',
      '장범준',
      '장재인',
      '장혜진',
      '적재',
      '전미도',
      '전상근',
      '전소미',
      '전효성',
      '정기고',
      '정동하',
      '정승환',
      '정용화 (CNBLUE)',
      '정은지',
      '정인',
      '정준영',
      '정준일',
      '정키',
      '정형돈',
      '제니 (JENNIE)',
      '제시 (Jessi)',
      '조권',
      '조용필',
      '조이 (JOY)',
      '조정석',
      '존박',
      '종현 (JONGHYUN)',
      '지나',
      '지누션',
      '지민',
      '지아',
      '지코 (ZICO)',
      '지투 (G2)',
      '찬열 (CHANYEOL)',
      '창모 (CHANGMO)',
      '처진 달팽이 (유재석 & 이적)',
      '철싸 (노홍철 & 싸이)',
      '청하',
      '첸 (CHEN)',
      '치타 (CHEETAH)',
      '카라',
      '케이시 (Kassy)',
      '케이윌',
      '크레용팝',
      '키썸 (Kisum)',
      '타이거JK, 윤미래, 비지 (Bizzy)',
      '태양',
      '태연 (TAEYEON)',
      '토이',
      '투개월',
      '트러블메이커',
      '티아라',
      '틴탑',
      '파리돼지앵 (정형돈 & 정재형)',
      '펀치 (Punch)',
      '포맨 (4MEN)',
      '포스트맨(Postmen)',
      '폴킴',
      '프라이머리',
      '플라이 투 더 스카이',
      '하동균',
      '하은 (포맨)',
      '하이라이트 (Highlight)',
      '한동근',
      '행주',
      '허각',
      '헤이즈 (Heize)',
      '혁오 (HYUKOH)',
      '현아',
      '형돈이와 대준이',
      '형용돈죵 (정형돈 & G-DRAGON)',
      '호미들',
      '화사 (Hwa Sa)',
      '환불원정대',
      '황광희 X 개코',
      '황인욱',
      '황치열',
      '효린',
      '휘성 (Realslow)',
      '휘인 (Whee In)'
      ];

$(document).ready(function() {
    $("#search").autocomplete(availableTags,{ 
        matchContains: true,
        selectFirst: false
    });
});